# Boost version 1_80_0
function(link_boost target MOD)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_atomic.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_chrono.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_container.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_context.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_contract.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_coroutine.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_date_time.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_fiber.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_filesystem.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_graph.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_iostreams.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_json.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_locale.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_log.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_log_setup.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_math_c99.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_math_c99f.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_math_c99l.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_math_tr1.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_math_tr1f.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_math_tr1l.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_nowide.so)
#    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_numpy310.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_prg_exec_monitor.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_program_options.so)
#    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_python310.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_random.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_regex.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_serialization.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_stacktrace_addr2line.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_stacktrace_basic.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_stacktrace_noop.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_system.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_thread.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_timer.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_type_erasure.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_unit_test_framework.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_wave.so)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/stage/lib/libboost_wserialization.so)
    target_include_directories(${target} SYSTEM ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost)
endfunction()
