# Boost version 1_80_0
function(link_boost target MOD)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_atomic.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_chrono.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_container.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_context.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_contract.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_coroutine.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_date_time.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_fiber.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_filesystem.a)
#    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_graph.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_iostreams.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_json.a)
#    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_locale.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_log.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_log_setup.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_math_c99.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_math_c99f.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_math_c99l.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_math_tr1.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_math_tr1f.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_math_tr1l.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_nowide.a)
#    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_numpy310.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_prg_exec_monitor.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_program_options.a)
#    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_python310.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_random.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_regex.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_serialization.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_stacktrace_addr2line.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_stacktrace_basic.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_stacktrace_noop.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_system.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_thread.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_timer.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_type_erasure.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_unit_test_framework.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_wave.a)
    target_link_libraries(${target} ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/lib/libboost_wserialization.a)
    target_include_directories(${target} SYSTEM ${MOD} ${PROJECT_SOURCE_DIR}/thirdparty/boost/include)
endfunction()
